### ISSUE TITLE
All-Time view broken

### ISSUE THREAD

**Issue by alexreinking** [intabeta/inta#1]
The nav bar is totally broken in the all-time view. See the attached screenshot for reference.

![image](https://f.cloud.github.com/assets/169273/580493/6a90c7de-c889-11e2-9f48-62bf2ba18644.png)

**Comment by bwloeb** [comment]
Yea I know, I mentioned it to you yesterday. It's my one obvious bug but I
can't find it...

**Comment by alexreinking** [comment]
Yeah, it could be a bit tricky... are all of the pages being rendered to the same template? Have you looked at the page's HTML in the Chrome Inspector?

It's good to track tricky bugs like these in the issues panel.

**Comment by bwloeb** [comment]
Not too good at using that yet so didn't use it for this. And it's all in
Brian.html no template...

**Comment by bwloeb** [comment]
Driving now so I can't look either

**Comment by bwloeb** [comment]
Driving now so I can't look either.
